spring.application.name: kshoong

#server:
#  port: 9090

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/kshoong
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: kshoong_root
#    password: kshoong!@34

server:
  port: 8899
  ssl:
    key-store: classpath:certificate.p12
    key-store-password: ksh123!@#
    key-store-type: PKCS12
